import { gridFromPattern, gridsFromPatterns } from '../shared/grid';
import type { MascotAsset } from '../shared/types';

const IDLE_OPEN = '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########';
const IDLE_BLINK = '.##....##.|###....###|##########|##########|##########|##o##*#o##|##########';

function motionAsset(
  id: string,
  key: string,
  fps: number,
  frames: ReadonlyArray<string>,
  meta: Omit<MascotAsset, 'id' | 'mascot' | 'key' | 'kind' | 'frames' | 'fps'>,
): MascotAsset {
  return {
    id,
    mascot: 'peek',
    key,
    kind: 'motion',
    fps,
    frames: gridsFromPatterns(frames),
    ...meta,
  };
}

function poseAsset(
  id: string,
  key: string,
  frame: string,
  meta: Omit<MascotAsset, 'id' | 'mascot' | 'key' | 'kind' | 'grid'>,
): MascotAsset {
  return {
    id,
    mascot: 'peek',
    key,
    kind: 'pose',
    grid: gridFromPattern(frame),
    ...meta,
  };
}

const PURR = [
  '.##....##.|###....###|##########|##########|##########|##oo*#oo##|##########',
  '.##....##.|###....###|##########|##########|##########|##oo**oo##|##########',
  '.##....##.|###....###|##########|##########|##########|##oo*#oo##|##########',
  '.##....##.|###....###|##########|##########|##########|##o##*#o##|##########',
  '.##....##.|###....###|##########|##########|##########|##oo**oo##|##########',
  '.##....##.|###....###|##########|##########|##########|##oo*#oo##|##########',
];

const NAP = [
  '.##....##.|###....###|##########|##########|##########|#####*####|##########',
  '.##....##.|###....###|##########|##########|##########|##########|##########',
  '.##....##.|###....###|##########|##########|##########|#####*####|##########',
  '.##....##.|###....###|##########|##########|##########|##########|##########',
];

const POSE_FAR_LEFT = '.#.....##.|##.....###|##########|##########|o####o####|o##*#o####|##########';
const POSE_LEFT = '.##....###|###....###|##########|##########|#o####o###|#o##*#o###|##########';
const POSE_CENTER = '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########';
const POSE_RIGHT = '###....##.|###....###|##########|##########|###o####o#|###o#*##o#|##########';
const POSE_FAR_RIGHT = '.##.....#.|###.....##|##########|##########|####o####o|####o#*##o|##########';

export const PEEK_MOTION_ASSETS: ReadonlyArray<MascotAsset> = [
  motionAsset('peek.motion.idle', 'idle', 2, [
    IDLE_OPEN, IDLE_OPEN, IDLE_OPEN, IDLE_OPEN,
    IDLE_OPEN, IDLE_OPEN, IDLE_OPEN, IDLE_OPEN,
    IDLE_BLINK,
  ], {
    label: 'Idle',
    summary: 'Rare slow blink with a steady rest state.',
    usage: 'Default rest state in the navbar.',
    status: 'active',
    tags: ['core', 'nav'],
    motionKind: 'loop',
    loop: true,
    order: 10,
  }),
  motionAsset('peek.motion.hide', 'hide', 12, [
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '..........|.##....##.|###....###|##########|##o####o##|##o##*#o##|##########',
    '..........|..........|.##....##.|###....###|##o####o##|##o##*#o##|##########',
    '..........|..........|..........|.##....##.|##o####o##|##o##*#o##|##########',
    '..........|..........|..........|..........|.##....##.|##o##*#o##|##########',
    '..........|..........|..........|..........|..........|##########|##########',
  ], {
    label: 'Hide',
    summary: 'Drops below the ledge, then peeks back up.',
    usage: 'Useful when the mascot should retreat without disappearing entirely.',
    status: 'active',
    tags: ['core', 'transition'],
    motionKind: 'loop',
    loop: true,
    order: 20,
  }),
  motionAsset('peek.motion.pop', 'pop', 16, [
    '..........|..........|..........|..........|..........|##########|##########',
    '..........|..........|..........|..........|.##....##.|#####*####|##########',
    '..........|..........|.##....##.|###....###|##o####o##|##o##*#o##|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '###....###|###....###|##########|#oo####oo#|#oo####oo#|#####*####|##########',
    '###....###|###....###|##########|#oo####oo#|#oo####oo#|#####*####|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
  ], {
    label: 'Pop',
    summary: 'Fast surprise burst with wide eyes.',
    usage: 'Best for sudden reveals or high-attention moments.',
    status: 'active',
    tags: ['core', 'burst'],
    motionKind: 'loop',
    loop: true,
    order: 30,
  }),
  motionAsset('peek.motion.curious', 'curious', 10, [
    '.##....##.|###.......|##########|##########|#o####o###|#o##*#o###|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.##....##.|.......###|##########|##########|###o####o#|###o#*##o#|##########',
    '.##....##.|.......###|##########|##########|###o####o#|###o#*##o#|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
  ], {
    label: 'Curious',
    summary: 'Head tilt with tracking eyes.',
    usage: 'Triggered when desktop nav links are hovered.',
    status: 'active',
    tags: ['core', 'nav', 'hover'],
    motionKind: 'loop',
    loop: true,
    order: 40,
  }),
  motionAsset('peek.motion.purr', 'purr', 8, PURR, {
    label: 'Purr',
    summary: 'Squinting eyes and a pulsing nose.',
    usage: 'The friendly baseline for positive reactions.',
    status: 'active',
    tags: ['core', 'warm'],
    motionKind: 'loop',
    loop: true,
    order: 50,
  }),
  motionAsset('peek.motion.dart', 'dart', 24, [
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.##....##.|###....###|##########|##########|#o####o###|#o##*#o###|##########',
    '.##....##.|###....###|##########|##########|#o####o###|#o##*#o###|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.##....##.|###....###|##########|##########|###o####o#|###o#*##o#|##########',
    '.##....##.|###....###|##########|##########|###o####o#|###o#*##o#|##########',
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.##....##.|###....###|##########|##########|##########|##o##*#o##|##########',
  ], {
    label: 'Dart',
    summary: 'Rapid eye flick left to right.',
    usage: 'Used for navbar hover and fast-scroll reactions.',
    status: 'active',
    tags: ['core', 'nav', 'fast'],
    motionKind: 'loop',
    loop: true,
    order: 60,
  }),
  motionAsset('peek.motion.nap', 'nap', 3, NAP, {
    label: 'Nap',
    summary: 'Closed eyes with a slow pulse.',
    usage: 'Base sleepy state before aliasing.',
    status: 'active',
    tags: ['core', 'rest'],
    motionKind: 'loop',
    loop: true,
    order: 70,
  }),
  motionAsset('peek.motion.scan', 'scan', 7, [
    POSE_LEFT, POSE_LEFT, POSE_FAR_LEFT, POSE_FAR_LEFT, POSE_LEFT,
    POSE_CENTER,
    POSE_RIGHT, POSE_FAR_RIGHT, POSE_FAR_RIGHT, POSE_RIGHT, POSE_RIGHT,
    POSE_CENTER, POSE_CENTER, POSE_LEFT,
  ], {
    label: 'Scan',
    summary: 'Off-center search pattern across five head poses.',
    usage: 'Ambient search motion for sidebar and 404 interactions.',
    status: 'active',
    tags: ['tracking', 'ambient'],
    motionKind: 'loop',
    loop: true,
    order: 80,
  }),
  motionAsset('peek.motion.alert', 'alert', 14, [
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.##....##.|.##....##.|###....###|##########|##oo##oo##|##oo#*oo##|##########',
    '.##....##.|.##....##.|###....###|##########|##oo##oo##|##oo**oo##|##########',
    '.##....##.|.##....##.|###....###|##########|##oo##oo##|##oo#*oo##|##########',
    '.##....##.|.##....##.|###....###|##########|##oo##oo##|##oo#*oo##|##########',
  ], {
    label: 'Alert',
    summary: 'Snaps to center and opens into 2x2 eyes.',
    usage: 'Best for short attention grabs or sudden state changes.',
    status: 'active',
    tags: ['utility', 'burst'],
    motionKind: 'one-shot',
    loop: false,
    previewLoop: true,
    order: 90,
  }),
  motionAsset('peek.motion.dissolve', 'dissolve', 14, [
    '.##....##.|###....###|##########|##########|##o####o##|##o##*#o##|##########',
    '.#.....##.|##.....###|#########.|##.#######|##o####o##|##o##*#o##|#########.',
    '.#.....#..|##.....##.|##.######.|#..#######|#.o####.##|##o##*#o##|##.#####.#',
    '.#......#.|.#.....##.|##.####...|...######.|#.o##..#..|.#o##*#.o#|.#.#.###..',
    '..#.....#.|..#.....#.|.#...##...|...#####..|..#....#..|.#...*#...|.#...#....',
    '..#.......|..........|.....##...|.....#....|.......#..|.....*....|.#........',
    '..........|..........|.....#....|..........|..........|.....*....|..........',
    '..........|..........|..........|..........|..........|.....*....|..........',
  ], {
    label: 'Dissolve',
    summary: 'Pixels scatter away and the nose lingers last.',
    usage: 'Exit transition when the mascot should vanish with intent.',
    status: 'active',
    tags: ['utility', 'transition'],
    motionKind: 'one-shot',
    loop: false,
    previewLoop: true,
    order: 100,
  }),
  poseAsset('peek.pose.base', 'base', IDLE_OPEN, {
    label: 'Base',
    summary: 'Static brand grid used by SVG consumers.',
    status: 'active',
    tags: ['brand', 'static'],
    motionKind: 'pose',
    order: 110,
  }),
  poseAsset('peek.pose.track-far-left', 'track_far_left', POSE_FAR_LEFT, {
    label: 'Track Far Left',
    summary: 'Hard left static pose.',
    usage: 'Cursor-locked pose for the furthest left tracking bucket.',
    status: 'active',
    tags: ['tracking', 'pose'],
    motionKind: 'pose',
    order: 120,
  }),
  poseAsset('peek.pose.track-left', 'track_left', POSE_LEFT, {
    label: 'Track Left',
    summary: 'Left static pose.',
    usage: 'Cursor-locked pose for left tracking.',
    status: 'active',
    tags: ['tracking', 'pose'],
    motionKind: 'pose',
    order: 130,
  }),
  poseAsset('peek.pose.track-center', 'track_center', POSE_CENTER, {
    label: 'Track Center',
    summary: 'Centered static pose.',
    usage: 'Neutral lock state when the mascot faces forward.',
    status: 'active',
    tags: ['tracking', 'pose'],
    motionKind: 'pose',
    order: 140,
  }),
  poseAsset('peek.pose.track-right', 'track_right', POSE_RIGHT, {
    label: 'Track Right',
    summary: 'Right static pose.',
    usage: 'Cursor-locked pose for right tracking.',
    status: 'active',
    tags: ['tracking', 'pose'],
    motionKind: 'pose',
    order: 150,
  }),
  poseAsset('peek.pose.track-far-right', 'track_far_right', POSE_FAR_RIGHT, {
    label: 'Track Far Right',
    summary: 'Hard right static pose.',
    usage: 'Cursor-locked pose for the furthest right tracking bucket.',
    status: 'active',
    tags: ['tracking', 'pose'],
    motionKind: 'pose',
    order: 160,
  }),
  motionAsset('peek.motion.happy', 'happy', 8, PURR, {
    label: 'Happy',
    summary: 'Positive alias that reuses purr.',
    usage: 'Triggered when the active navbar section changes.',
    status: 'active',
    tags: ['alias', 'nav', 'positive'],
    motionKind: 'alias',
    aliasOf: 'peek.motion.purr',
    loop: true,
    order: 170,
  }),
  motionAsset('peek.motion.sleepy', 'sleepy', 4, NAP, {
    label: 'Sleepy',
    summary: 'Idle alias that reuses nap.',
    usage: 'Triggered after long inactivity in the navbar.',
    status: 'active',
    tags: ['alias', 'nav', 'idle-timeout'],
    motionKind: 'alias',
    aliasOf: 'peek.motion.nap',
    loop: true,
    order: 180,
  }),
];
