import { useEffect, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowUpRight, Star, X } from "lucide-react";
import CliCubeHero from "@/components/project-cards/CliCubeHero";
import HarmonicWaveHero from "@/components/project-cards/HarmonicWaveHero";

// ---------------------------------------------------------------------------
// Data model. Each project carries the ONE hero that best represents it:
//   terminal   → show the actual output/syntax (CLIs, configs)
//   screenshot → show real pixels (visual products like themes)
//   generated  → show what the project produces (image services)
// ---------------------------------------------------------------------------

type Hero =
  | { kind: "waves" }
  | { kind: "screenshot"; src: string; url: string; alt: string }
  | { kind: "generated"; src: string; caption: string; alt: string }
  | { kind: "cube" };

interface ShowcaseProject {
  id: string;
  name: string;
  type: string;
  url: string;
  blurb: string;
  story: string[];
  tags: string[];
  stars: number | null;
  hero: Hero;
}

const projects: ShowcaseProject[] = [
  {
    id: "tutubetterrules",
    name: "TutuBetterRules",
    type: "Proxy Rules",
    url: "https://github.com/bunizao/TutuBetterRules",
    blurb: "Cross-platform proxy rules — Surge-first, syncs to Clash, Shadowrocket & QX.",
    story: [
      "It started as my own Surge config — the kind you keep tweaking at 1am until traffic finally routes the way you want. Then it grew into one source of truth that compiles out to Surge, Clash, Shadowrocket, and Quantumult X.",
      "Now ~400 people run it. Modules, rewrites, and policy groups kept in sync, so you update once instead of babysitting four bespoke configs.",
    ],
    tags: ["Surge", "Clash", "Shadowrocket", "QX"],
    stars: 391,
    hero: { kind: "waves" },
  },
  {
    id: "cli-tools",
    name: "CLI Tools",
    type: "Student Automation",
    url: "https://github.com/bunizao?tab=repositories&q=cli",
    blurb: "A cluster of small CLIs — Moodle, Ed, OnTrack, attendance — that automate student busywork.",
    story: [
      "Five small command-line tools for the tedious parts of being a student: pulling assignments from Moodle, browsing Ed threads, syncing OnTrack tasks, submitting attendance, Okta SSO. Each does one thing, from the shell.",
      "Some ship an MCP server too, so an agent can drive them. The boring parts of uni, scripted away.",
    ],
    tags: ["CLI", "MCP", "Automation"],
    stars: null,
    hero: { kind: "cube" },
  },
  {
    id: "attegi",
    name: "Attegi",
    type: "Ghost Theme",
    url: "https://github.com/bunizao/Attegi",
    blurb: "An elegant, dynamic Ghost theme — modern, mobile-first, deeply Ghost-native.",
    story: [
      "Attegi is a Ghost theme with a quiet editorial spine — sharp type, fast pages, and a dark mode that actually looks designed. Liquid-glass buttons, a real table of contents, code blocks that don't fight you.",
      "27 blogs run it. It's the theme I wished existed when I set up my own.",
    ],
    tags: ["Ghost", "Theme", "TailwindCSS"],
    stars: 27,
    hero: {
      kind: "screenshot",
      src: "https://raw.githubusercontent.com/bunizao/Attegi/main/screenshots/homepage-dark.png",
      url: "attegi.tuuhub.com",
      alt: "Attegi Ghost theme homepage in dark mode",
    },
  },
  {
    id: "ogis",
    name: "ogis",
    type: "OG Image Service",
    url: "https://github.com/bunizao/ogis",
    blurb: "Dynamic Open Graph images — themed, signed, generated at the edge.",
    story: [
      "ogis turns a URL into a share image. Pass a title and a site name, get back a clean OG card rendered on the edge — custom themes, optional request signing so nobody hotlinks your generator.",
      "The image on this card? Generated live by ogis. That's the whole pitch.",
    ],
    tags: ["Next.js", "OG Image", "Edge"],
    stars: 5,
    hero: {
      kind: "generated",
      src: "https://og.tuuhub.com/api/og?title=ogis&site=Open%20Graph%20Service",
      caption: "Generated live by ogis",
      alt: "Open Graph image generated by ogis",
    },
  },
];

// ---------------------------------------------------------------------------
// Hero renderers
// ---------------------------------------------------------------------------

function ScreenshotHero({ hero }: { hero: Extract<Hero, { kind: "screenshot" }> }) {
  return (
    <div className="flex h-full w-full flex-col bg-[#0c0d10]">
      <div className="flex items-center gap-1.5 border-b border-white/10 px-3 py-2">
        <span className="h-2 w-2 rounded-full bg-white/20" />
        <span className="h-2 w-2 rounded-full bg-white/20" />
        <span className="h-2 w-2 rounded-full bg-white/20" />
        <span className="ml-2 flex-1 truncate rounded-[4px] bg-white/[0.06] px-2 py-0.5 text-center font-code text-[10px] text-white/40">
          {hero.url}
        </span>
      </div>
      <div className="relative flex-1 overflow-hidden">
        <img
          src={hero.src}
          alt={hero.alt}
          loading="lazy"
          className="absolute inset-0 h-full w-full object-cover object-top transition-transform duration-700 ease-out group-hover:scale-105"
        />
      </div>
    </div>
  );
}

function GeneratedHero({ hero }: { hero: Extract<Hero, { kind: "generated" }> }) {
  return (
    <div className="relative h-full w-full overflow-hidden bg-[#0c0d10]">
      <img
        src={hero.src}
        alt={hero.alt}
        loading="lazy"
        className="absolute inset-0 h-full w-full object-cover object-left-bottom transition-transform duration-700 ease-out group-hover:scale-105"
      />
      <span className="absolute bottom-2 right-2 rounded-full border border-white/15 bg-black/50 px-2 py-0.5 font-code text-[10px] text-white/70 backdrop-blur-md">
        {hero.caption}
      </span>
    </div>
  );
}

function renderHero(hero: Hero) {
  switch (hero.kind) {
    case "waves":
      return <HarmonicWaveHero />;
    case "screenshot":
      return <ScreenshotHero hero={hero} />;
    case "generated":
      return <GeneratedHero hero={hero} />;
    case "cube":
      return <CliCubeHero />;
  }
}

function StarBadge({ stars }: { stars: number }) {
  return (
    <span className="inline-flex shrink-0 items-center gap-1 rounded-full border border-white/15 bg-white/10 px-2.5 py-1 font-code text-[12px] font-semibold text-white/85 backdrop-blur-md">
      <Star className="h-3 w-3 fill-amber-300 text-amber-300" />
      {stars}
    </span>
  );
}

// ---------------------------------------------------------------------------
// Card: collapsed (L0) ↔ expanded (L1), morphing via shared layoutId.
// ---------------------------------------------------------------------------

function ProjectShowcaseCard({ project }: { project: ShowcaseProject }) {
  const [open, setOpen] = useState(false);
  const reduce = useReducedMotion();

  const ids = {
    card: `card-${project.id}`,
    hero: `hero-${project.id}`,
    title: `title-${project.id}`,
  };

  const spring = reduce
    ? { duration: 0 }
    : ({ type: "spring", stiffness: 210, damping: 26, mass: 0.9 } as const);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("keydown", onKey);
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = prevOverflow;
    };
  }, [open]);

  return (
    <>
      {/* ---------- L0 ---------- */}
      <motion.button
        layoutId={ids.card}
        type="button"
        onClick={() => setOpen(true)}
        transition={spring}
        whileHover={reduce ? undefined : { y: -5 }}
        className="group relative block w-[340px] max-w-full overflow-hidden rounded-[18px] border border-white/12 bg-neutral-950/85 text-left text-white shadow-2xl shadow-black/40 outline-none backdrop-blur-xl focus-visible:ring-2 focus-visible:ring-white/60"
      >
        <motion.div
          layoutId={ids.hero}
          className="relative aspect-[16/10] w-full overflow-hidden"
        >
          {renderHero(project.hero)}
        </motion.div>

        <div className="p-5">
          <p className="font-code text-[10px] uppercase tracking-[0.14em] text-white/35 transition-colors duration-300 group-hover:text-white/55">
            {project.type}
          </p>
          <div className="mt-1.5 flex items-center justify-between gap-3">
            <motion.h3
              layoutId={ids.title}
              className="relative font-display text-[22px] font-extrabold leading-none tracking-tight"
            >
              {project.name}
              <span className="absolute -bottom-1 left-0 h-px w-0 bg-white/70 transition-all duration-700 ease-out group-hover:w-full" />
            </motion.h3>
            {project.stars != null && <StarBadge stars={project.stars} />}
          </div>

          <p className="mt-3 font-sans text-[13.5px] leading-relaxed text-white/55 transition-colors duration-300 group-hover:text-white/75">
            {project.blurb}
          </p>

          <div className="mt-4 flex items-center justify-end">
            <span className="inline-flex items-center gap-1 font-code text-[11px] font-semibold uppercase tracking-wide text-white/40 transition-colors duration-300 group-hover:text-white/70">
              Tell me more
              <ArrowUpRight className="h-0 w-0 scale-0 transition-all duration-300 group-hover:h-3.5 group-hover:w-3.5 group-hover:scale-100" />
            </span>
          </div>
        </div>
      </motion.button>

      {/* ---------- L1 ---------- */}
      <AnimatePresence>
        {open && (
          <div className="fixed inset-0 z-50 grid place-items-center p-4 sm:p-6">
            <motion.div
              className="absolute inset-0 bg-black/60 backdrop-blur-sm"
              onClick={() => setOpen(false)}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            />

            <motion.div
              layoutId={ids.card}
              role="dialog"
              aria-modal="true"
              aria-label={project.name}
              transition={spring}
              className="relative z-10 w-[680px] max-w-full overflow-hidden rounded-[22px] border border-white/12 bg-neutral-950/95 text-white shadow-2xl shadow-black/60 backdrop-blur-xl"
            >
              <motion.div
                layoutId={ids.hero}
                className="relative aspect-[16/9] w-full overflow-hidden"
              >
                {renderHero(project.hero)}
              </motion.div>

              <button
                type="button"
                onClick={() => setOpen(false)}
                aria-label="Close"
                className="absolute right-4 top-4 grid h-9 w-9 place-items-center rounded-full border border-white/15 bg-black/50 text-white/80 backdrop-blur-md transition-colors hover:bg-black/70 hover:text-white"
              >
                <X className="h-4 w-4" />
              </button>

              <div className="p-6 sm:p-8">
                <p className="mb-2 font-code text-[11px] uppercase tracking-[0.14em] text-white/40">
                  {project.type}
                </p>
                <div className="flex items-center justify-between gap-3">
                  <motion.h3
                    layoutId={ids.title}
                    className="font-display text-[34px] font-extrabold leading-none tracking-tight sm:text-[40px]"
                  >
                    {project.name}
                  </motion.h3>
                  {project.stars != null && <StarBadge stars={project.stars} />}
                </div>

                <motion.div
                  initial={reduce ? false : { opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: reduce ? 0 : 0.12, duration: 0.3 }}
                >
                  <div className="mt-4 flex flex-wrap gap-2">
                    {project.tags.map((tag) => (
                      <span
                        key={tag}
                        className="rounded-full border border-white/12 bg-white/[0.06] px-3 py-1 font-code text-[11px] text-white/65"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>

                  <div className="mt-5 space-y-4">
                    {project.story.map((paragraph, i) => (
                      <p
                        key={i}
                        className="font-sans text-[15px] leading-relaxed text-white/75"
                      >
                        {paragraph}
                      </p>
                    ))}
                  </div>

                  <a
                    href={project.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="mt-7 inline-flex items-center gap-1.5 border-b border-white/25 pb-0.5 font-code text-[13px] font-semibold uppercase tracking-wide text-white/80 transition-colors hover:border-white hover:text-white"
                  >
                    View on GitHub
                    <ArrowUpRight className="h-4 w-4" />
                  </a>
                </motion.div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </>
  );
}

export default function ProjectShowcase() {
  return (
    <div className="flex flex-wrap items-start justify-center gap-6">
      {projects.map((project) => (
        <ProjectShowcaseCard key={project.id} project={project} />
      ))}
    </div>
  );
}
